name: Auto PR on Main Merge

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  version-bump:
    runs-on: ubuntu-latest
    if: "!contains(toJSON(github.event.commits.*.message), 'chore(release)')"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - uses: fregante/setup-git-user@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: bump version
        run: npx standard-version --no-verify

      - name: Get latest tag
        uses: actions/github-script@v6
        with:
          script: |
            git fetch origin main
            latestTag=$(git describe --tags --abbrev=0 origin/main)
            echo "::set-output name=latestTag::$latestTag"

      
      - name: Create new branch
        run: |
          git checkout -b release/{{ steps.get-latest-tag.outputs.latestTag }}

      - name: Push changes
        run: git push -f origin release/{{ steps.get-latest-tag.outputs.latestTag }}

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          pr_title: 'Chore: new version bump PR'
          destination_branch: main
          source_branch: release/{{ steps.get-latest-tag.outputs.latestTag }}
          pr_body: 'This PR was automatically created after a merge to main.'
          # Optional: labels to add to the PR
          pr_label: auto-generated
