name: Bump Version on Merge to main

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write  # Permission required for direct merge

jobs:
  version-bump:
    runs-on: ubuntu-latest
    if: "!contains(toJSON(github.event.commits.*.message), 'chore(release)')"
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - uses: fregante/setup-git-user@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: bump version
        run: npx standard-version --no-verify
      
      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=latest-tag::$latest_tag"
      
      - name: Create new branch
        run: git checkout -b release/${{ steps.get_latest_tag.outputs.latest-tag }}

      - name: Push changes
        run: git push -f origin release/${{ steps.get_latest_tag.outputs.latest-tag }}

      - name: Merge to main
        run: |
          git checkout main
          git merge release/${{ steps.get_latest_tag.outputs.latest-tag }}
          git push origin main
